### ISSUE TITLE
save model not working with auto conversion.

### ISSUE THREAD

**Issue by jangrasukhveer** [LGE-ARC-AdvancedAI/auptimizer#17]
Hi i am facing issue with save model if auto conversion is used.
Step1:
In training script i have added the 
      **aup_save_model(save_model, model)**

and save_model call back is implemented as 
    **def save_model(model):
      import os
      print("save_model...")
      os.makedirs('save_model')
      model.save('./save_model/mnist.h5')**

Step2: convert the script in hpo format.
 **python -m aup.convert  train_script  aup_config function**
Step3: Training with hpo converted file
**python -m aup experiment.json** 
Call back written for saving the model (**save_model**) is not getting hit.
I doubt the aup.convert is not able to handle the save_model changes

Result: model is not getting saved

**Comment by guojunyao419** [comment]
Hi @jangrasukhveer, thank you for spotting this issue. 

Currently, ''aup.convert'' is in beta version, meaning that it does not fully support the new features in Auptimizer v2.0 (such as "save_model"). We will add this support in a future release.

In this case, I would suggest you doing a manual training script conversion or using a decorator. Please see [script with decorator](https://github.com/LGE-ARC-AdvancedAI/auptimizer/blob/master/Examples/mnist_keras_save_model/mnist.py) and [script without decorator](https://github.com/LGE-ARC-AdvancedAI/auptimizer/blob/master/Examples/mnist_keras_save_model/mnist_wo_decorator.py) for reference. Thanks!

**Comment by jangrasukhveer** [comment]
Hi,
Thank you, manual save_model part is working fine.
