### ISSUE TITLE
Question: Py3 support?

### ISSUE THREAD

**Issue by leopd** [LGE-ARC-AdvancedAI/auptimizer#3]
**Is your feature request related to a problem? Please describe.**
Does auptimizer work with any python3.x versions?  The `requirements.txt` file confuses me referencing both 2.7 and 3.x.

**Describe the solution you'd like**
I'd like to see py3 support.

**Comment by jiayiliu** [comment]
It works for python3.  The requirement file adjusts the version requirements for different HPO algorithms, e.g. `hpbandster` works with python3 only at the time of writing.

**Comment by leopd** [comment]
Thanks!
